post_install() {
echo -e "Accessing serial\n-------------------\nThe arduino board communicates with the computer via a serial connection or a serial over USB connection. So the user needs read/write access to the serial device file. Udev creates files in /dev/tts/ owned by group uucp so adding the user to the uucp group gives the required read/write access. If you are planing to use the default Java IDE, add your user to the lock group for /var/lock/lockdev access.\n# gpasswd -a USER uucp\n# gpasswd -a USER lock"
}

